# src/battleships/config/fleet.yml

basic_fleet_1:
  roster: default
  ships:
    aircraft_carrier: { quantity: 1, symbol: 'A' }
    battleship: { quantity: 1, symbol: 'B' }
    cruiser: { quantity: 1, symbol: 'D' }
    destroyer: { quantity: 2, symbol: 'D' }
    submarine: { quantity: 2, symbol: 'S' }
