# src/battleships/config/player.yml

aircraft_carrier:
  position:
    - ((0,0), (0, 1), (0, 2), (0, 3), (0, 4))

battleship:
  position:
    - ((1, 0), (2, 0), (3, 0), (4, 0))

cruiser:
  position:
    - ((4, 1), (4, 2), (4, 3), (4, 4))

destroyer:
  positions:
    - ((3, 2), (3, 3))
    - ((2, 3), (2, 4))

submarine:
  positions:
    - ((3, 4))
    - ((1, 1))
