# src/battleships/config/rosters.yml

default:  # id
  roster:
    aircraft_carrier: { size: 5, is_cloaked: false }
    battleship: { size: 4, is_cloaked: false }
    cruiser: { size: 3, is_cloaked: false }
    destroyer: { size: 2, is_cloaked: false }
    submarine: { size: 1, is_cloaked: false }
