# src/battleships/config/rosters.yml

default:  # id
  roster:
    aircraft_carrier: { size: 5 }
    battleship: { size: 4 }
    cruiser: { size: 3 }
    destroyer: { size: 2, is_cloaked: false }
    submarine: { size: 1 }
